## Exercise 63 - More for Loops

# Create a list that contains at least 20 different numbers that aren’t sorted
# Don’t use range for the generation of the list
# Write a loop that runs over all elements of the list and adds them all up (sum up all elements)
# Write a second loop that tells the user for each element whether it is bigger or lower than a number specified by him
# This number should be generated by using input before the start of the loop

list1 = [2, 5, 12, 80, 34, 6, 25, 48, 5, 4, 100, 1, 3, 22, 56, 90, 21, 51, 39, 77]
sum = 0

 # Sum up all elements
for i in list1:
    sum = sum + i
print(f"The sum of all elements in the list is {sum}")

#Compare user input to each element in the list
user_input = int(input("Specify a number: "))
for i in list1:
    if i > user_input:
        print(f"Your number {user_input} is smaller than {i}")
    elif i < user_input:
        print(f"Your number {user_input} is bigger than {i}")
    else:
        print(f"Your number {user_input} is equal to {i}")
